### ISSUE TITLE
Upgrade ws package

### ISSUE THREAD

**Issue by stanleyxu2005** [ivaylopivanov/wamp-server#11]
The latest ws package is now 4.0, but this project is still using ws 2.0.
I did some basic benchmark with sending 20000 rpc to add two numbers in parallel. The result of using ws 2.0 is 1300ms (wamp.rt uses ws 0.8 with 2000ms), while using ws 4.0 (without check protocol) is 750ms. This is a huge impact and it is worth for a dependency upgrade.

But I notice that ws api has been changed a bit. There an error of obtain ip address during startup. Here is the description of the api change https://github.com/websockets/ws/pull/1099

**Comment by ivaylopivanov** [comment]
Will try to check this out in the following weeks

**Comment by stanleyxu2005** [comment]
Thank you for your fantastic work on supporting this, I know it is not easy.

Somehow, the new version throws some unhandled exceptions. I'm still investigating the root cause.
```
Unexpected shutting down... { Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TCP.onread (net.js:623:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

By the way, in package.json, you define package with fixed version number. You'd better use `"debug": "^2.2.0", "ws": "^4.0.0"`, so that npm/yarn will use the latest minor version (without any code break).

**Comment by ivaylopivanov** [comment]
https://github.com/websockets/ws/issues/1256 looks related. Will try to patch it.

**Comment by ivaylopivanov** [comment]
@stanleyxu2005 can you add
```js
this.socket.on('error', err => {
  const MSG = err.message;
  DEBUG('socket error "%s" for ID: %s and IP: %s', MSG, this.id, this.ip);
  if (MSG.indexOf('ECONNRESET') > -1) {
    this.close();
  }
});
```

to https://github.com/ivaylopivanov/wamp-server/blob/master/release/session.js#L207 and let me know how it goes.

**Comment by stanleyxu2005** [comment]
Looks good. The problem is gone. Thank you for the quick response

**Comment by ivaylopivanov** [comment]
No worries, will publish it later today or tomorrow.

**Comment by stanleyxu2005** [comment]
Cool. Now the wamp-server will have at least 200% performance increase!!

**Comment by stanleyxu2005** [comment]
I have created a PR with the fix (and other two)

**Comment by stanleyxu2005** [comment]
please watch https://github.com/ivaylopivanov/wamp-server/pull/20
