### ISSUE TITLE
Current build is failing

### ISSUE THREAD

**Issue by stanleyxu2005** [ivaylopivanov/wamp-server#18]
After typescript is upgraded from 1.8 to 2.7, https://github.com/ivaylopivanov/wamp-server/commit/24799bf06d91f654a7e79d7c6d41c819d99759ae#diff-b9cfc7f2cdf78a7f4b91a753d10865a2, the travis build output contains some errors (see https://travis-ci.org/ivaylopivanov/wamp-server/jobs/345909991). Please check.

**Comment by ivaylopivanov** [comment]
The new version of mocha has a problem with old node versions so I removed them. The build does not fail now.

**Comment by stanleyxu2005** [comment]
@ivaylopivanov where is your new code change? I still see the current commit is 66a58ca  "drop node v6 from travis"

**Comment by ivaylopivanov** [comment]
This is the commit that "fixes" the build. The build was failing because of timeouts. on node 6.x mocha didn't exit tests. I tried to add the additional `--exit` flag but that didn't help and I don't have time to search for other solutions

**Comment by stanleyxu2005** [comment]
I dont have much knowledge about typescript, I probably guess the build error is related to `@types/ws`. It's tsconfig uses "es6", but it seems the gulp script does not understand some dependency definitions.

https://hassantariqblog.wordpress.com/2017/03/12/angular2-resolve-typescript-ts2304-compilation-errors-in-visual-studio/
