### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Borvik** [ivaylopivanov/wamp-server#19]
This is not necessarily an error with wamp-server, but it is effecting a fully update to date environment.

Using wamp-server 0.0.7, which pulled in ws 4.0.0.

We are running wamp-server as the router using PM2, and getting the following error:
```
4|wrte | Error: read ECONNRESET
4|wrte |     at _errnoException (util.js:1022:11)
4|wrte |     at TCP.onread (net.js:615:25)
PM2        | App [wrte] with id [4] and pid [28463], exited with code [1] via signal [SIGINT]
3|wamp | lost { reason: null,
3|wamp |   message: null,
3|wamp |   retry_delay: 1.4510242141984613,
3|wamp |   retry_count: 1,
3|wamp |   will_retry: true }
```

The wrte app above, is just starting a wamp-server instance - and that's it:
```
server = require('wamp-server'),
    Server = new server({
      port: port,
      realms: [realm], // array or string 
    });
```
This is causing PM2 to see the error and restart the service.

It looks like this can be tied to this issue on the WebSockets library: https://github.com/websockets/ws/issues/1256

Looks like handling the error event from the socketinterface in SessionManager.createSession should take care of it: https://github.com/websockets/ws/issues/1256#issuecomment-367400288.

**Comment by stanleyxu2005** [comment]
Please refer this thread https://github.com/ivaylopivanov/wamp-server/issues/11
Basically the fix has been created, it will be merged soon.
For the time being, please stick to an older version. Thank you.

**Comment by Borvik** [comment]
Missed that in the comments of the other issue - that was essentially the solution referenced (just in a different area).  Thanks!

**Comment by stanleyxu2005** [comment]
please watch https://github.com/ivaylopivanov/wamp-server/pull/20
