### ISSUE TITLE
Error: Cannot find module 'wamp-server/src/server'

### ISSUE THREAD

**Issue by beLogiC** [ivaylopivanov/wamp-server#45]
I exactly did what the "example" folder said.

I just replaced the "../" with the modules name.
Raw:
`import Server from 'wamp-server/src/server';`

Replaced:
`import Server from '../src/server';`

and the rest:
```
export class WampRouter {
    private wss;

    constructor(port: number, realm: string) {
        this.wss = new Server({
            port: port,
            realms: [realm]
        });
   }
}
```

**Comment by ivaylopivanov** [comment]
Please follow the instructions in the readme - https://github.com/ivaylopivanov/wamp-server#usage
