### ISSUE TITLE
sometime register method, Always an error {"error":"wamp.error.procedure_already_exists","args":[],"kwargs":{}}

### ISSUE THREAD

**Issue by jonahzheng** [ivaylopivanov/wamp-server#9]
sometime register method, Always an error {"error":"wamp.error.procedure_already_exists","args":[],"kwargs":{}}.  such as, session.register('myfun', handle).
But by 'session.call' calls, not return success

**Comment by ivaylopivanov** [comment]
Can you provide a simple code example so I can reproduce it?

**Comment by stanleyxu2005** [comment]
Only crossbar supports to register one method multiple times (and use roundrobin to dispatch requests)

**Comment by ivaylopivanov** [comment]
I think we can close this now with the provided clarification.
